<?php

/**
 * @file
 *
 * Alternative to core menu management
 *
 * Needed when menus get to big to load on one page.
 */

/**
 * Implements hook_entity_type_build().
 *
 * Add the bigmenu form controllers to the entity type config object.
 */
function bigmenu_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['menu']->setFormClass('edit_bigmenu', 'Drupal\bigmenu\MenuFormLinkController');
  $entity_types['menu']->setFormClass('edit_bigmenu_slice', 'Drupal\bigmenu\MenuSliceFormController');
}
